//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleLegacy.ServerServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/Database.Model")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CastleLegacy.ServerServices.AccountCards[] AccountCardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CastleLegacy.ServerServices.AccountCastles[] AccountCastlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CastleLegacy.ServerServices.AccountFriends[] AccountFriendsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CastleLegacy.ServerServices.Profile[] ProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CastleLegacy.ServerServices.AccountCards[] AccountCards {
            get {
                return this.AccountCardsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountCardsField, value) != true)) {
                    this.AccountCardsField = value;
                    this.RaisePropertyChanged("AccountCards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CastleLegacy.ServerServices.AccountCastles[] AccountCastles {
            get {
                return this.AccountCastlesField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountCastlesField, value) != true)) {
                    this.AccountCastlesField = value;
                    this.RaisePropertyChanged("AccountCastles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CastleLegacy.ServerServices.AccountFriends[] AccountFriends {
            get {
                return this.AccountFriendsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountFriendsField, value) != true)) {
                    this.AccountFriendsField = value;
                    this.RaisePropertyChanged("AccountFriends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountStatus {
            get {
                return this.AccountStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountStatusField, value) != true)) {
                    this.AccountStatusField = value;
                    this.RaisePropertyChanged("AccountStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Account {
            get {
                return this.Id_AccountField;
            }
            set {
                if ((this.Id_AccountField.Equals(value) != true)) {
                    this.Id_AccountField = value;
                    this.RaisePropertyChanged("Id_Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CastleLegacy.ServerServices.Profile[] Profile {
            get {
                return this.ProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileField, value) != true)) {
                    this.ProfileField = value;
                    this.RaisePropertyChanged("Profile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountCards", Namespace="http://schemas.datacontract.org/2004/07/Database.Model")]
    [System.SerializableAttribute()]
    public partial class AccountCards : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CastleLegacy.ServerServices.Account AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CastleLegacy.ServerServices.Card CardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Id_AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_AccountCardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Id_CardField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CastleLegacy.ServerServices.Account Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CastleLegacy.ServerServices.Card Card {
            get {
                return this.CardField;
            }
            set {
                if ((object.ReferenceEquals(this.CardField, value) != true)) {
                    this.CardField = value;
                    this.RaisePropertyChanged("Card");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id_Account {
            get {
                return this.Id_AccountField;
            }
            set {
                if ((this.Id_AccountField.Equals(value) != true)) {
                    this.Id_AccountField = value;
                    this.RaisePropertyChanged("Id_Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_AccountCards {
            get {
                return this.Id_AccountCardsField;
            }
            set {
                if ((this.Id_AccountCardsField.Equals(value) != true)) {
                    this.Id_AccountCardsField = value;
                    this.RaisePropertyChanged("Id_AccountCards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id_Card {
            get {
                return this.Id_CardField;
            }
            set {
                if ((this.Id_CardField.Equals(value) != true)) {
                    this.Id_CardField = value;
                    this.RaisePropertyChanged("Id_Card");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountCastles", Namespace="http://schemas.datacontract.org/2004/07/Database.Model")]
    [System.SerializableAttribute()]
    public partial class AccountCastles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CastleLegacy.ServerServices.Account AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CastleLegacy.ServerServices.Castle CastleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Id_AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_AccountCastlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Id_CastleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CastleLegacy.ServerServices.Account Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CastleLegacy.ServerServices.Castle Castle {
            get {
                return this.CastleField;
            }
            set {
                if ((object.ReferenceEquals(this.CastleField, value) != true)) {
                    this.CastleField = value;
                    this.RaisePropertyChanged("Castle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id_Account {
            get {
                return this.Id_AccountField;
            }
            set {
                if ((this.Id_AccountField.Equals(value) != true)) {
                    this.Id_AccountField = value;
                    this.RaisePropertyChanged("Id_Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_AccountCastles {
            get {
                return this.Id_AccountCastlesField;
            }
            set {
                if ((this.Id_AccountCastlesField.Equals(value) != true)) {
                    this.Id_AccountCastlesField = value;
                    this.RaisePropertyChanged("Id_AccountCastles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id_Castle {
            get {
                return this.Id_CastleField;
            }
            set {
                if ((this.Id_CastleField.Equals(value) != true)) {
                    this.Id_CastleField = value;
                    this.RaisePropertyChanged("Id_Castle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountFriends", Namespace="http://schemas.datacontract.org/2004/07/Database.Model")]
    [System.SerializableAttribute()]
    public partial class AccountFriends : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CastleLegacy.ServerServices.Account AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CastleLegacy.ServerServices.Friend FriendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Id_AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_AccountFriendsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Id_FriendField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CastleLegacy.ServerServices.Account Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CastleLegacy.ServerServices.Friend Friend {
            get {
                return this.FriendField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendField, value) != true)) {
                    this.FriendField = value;
                    this.RaisePropertyChanged("Friend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id_Account {
            get {
                return this.Id_AccountField;
            }
            set {
                if ((this.Id_AccountField.Equals(value) != true)) {
                    this.Id_AccountField = value;
                    this.RaisePropertyChanged("Id_Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_AccountFriends {
            get {
                return this.Id_AccountFriendsField;
            }
            set {
                if ((this.Id_AccountFriendsField.Equals(value) != true)) {
                    this.Id_AccountFriendsField = value;
                    this.RaisePropertyChanged("Id_AccountFriends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id_Friend {
            get {
                return this.Id_FriendField;
            }
            set {
                if ((this.Id_FriendField.Equals(value) != true)) {
                    this.Id_FriendField = value;
                    this.RaisePropertyChanged("Id_Friend");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profile", Namespace="http://schemas.datacontract.org/2004/07/Database.Model")]
    [System.SerializableAttribute()]
    public partial class Profile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CastleLegacy.ServerServices.Account AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Id_AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_ProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LossesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ProfileImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VictoriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CastleLegacy.ServerServices.Account Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstLastName {
            get {
                return this.FirstLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstLastNameField, value) != true)) {
                    this.FirstLastNameField = value;
                    this.RaisePropertyChanged("FirstLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id_Account {
            get {
                return this.Id_AccountField;
            }
            set {
                if ((this.Id_AccountField.Equals(value) != true)) {
                    this.Id_AccountField = value;
                    this.RaisePropertyChanged("Id_Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Profile {
            get {
                return this.Id_ProfileField;
            }
            set {
                if ((this.Id_ProfileField.Equals(value) != true)) {
                    this.Id_ProfileField = value;
                    this.RaisePropertyChanged("Id_Profile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Losses {
            get {
                return this.LossesField;
            }
            set {
                if ((this.LossesField.Equals(value) != true)) {
                    this.LossesField = value;
                    this.RaisePropertyChanged("Losses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Names {
            get {
                return this.NamesField;
            }
            set {
                if ((object.ReferenceEquals(this.NamesField, value) != true)) {
                    this.NamesField = value;
                    this.RaisePropertyChanged("Names");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ProfileImage {
            get {
                return this.ProfileImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileImageField, value) != true)) {
                    this.ProfileImageField = value;
                    this.RaisePropertyChanged("ProfileImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondLastName {
            get {
                return this.SecondLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondLastNameField, value) != true)) {
                    this.SecondLastNameField = value;
                    this.RaisePropertyChanged("SecondLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Victories {
            get {
                return this.VictoriesField;
            }
            set {
                if ((this.VictoriesField.Equals(value) != true)) {
                    this.VictoriesField = value;
                    this.RaisePropertyChanged("Victories");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="http://schemas.datacontract.org/2004/07/Database.Model")]
    [System.SerializableAttribute()]
    public partial class Card : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CastleLegacy.ServerServices.AccountCards[] AccountCardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AttackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HealthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_CardField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CastleLegacy.ServerServices.AccountCards[] AccountCards {
            get {
                return this.AccountCardsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountCardsField, value) != true)) {
                    this.AccountCardsField = value;
                    this.RaisePropertyChanged("AccountCards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Attack {
            get {
                return this.AttackField;
            }
            set {
                if ((this.AttackField.Equals(value) != true)) {
                    this.AttackField = value;
                    this.RaisePropertyChanged("Attack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Health {
            get {
                return this.HealthField;
            }
            set {
                if ((this.HealthField.Equals(value) != true)) {
                    this.HealthField = value;
                    this.RaisePropertyChanged("Health");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Card {
            get {
                return this.Id_CardField;
            }
            set {
                if ((this.Id_CardField.Equals(value) != true)) {
                    this.Id_CardField = value;
                    this.RaisePropertyChanged("Id_Card");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Castle", Namespace="http://schemas.datacontract.org/2004/07/Database.Model")]
    [System.SerializableAttribute()]
    public partial class Castle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CastleLegacy.ServerServices.AccountCastles[] AccountCastlesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_CastleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CastleLegacy.ServerServices.AccountCastles[] AccountCastles {
            get {
                return this.AccountCastlesField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountCastlesField, value) != true)) {
                    this.AccountCastlesField = value;
                    this.RaisePropertyChanged("AccountCastles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Castle {
            get {
                return this.Id_CastleField;
            }
            set {
                if ((this.Id_CastleField.Equals(value) != true)) {
                    this.Id_CastleField = value;
                    this.RaisePropertyChanged("Id_Castle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Friend", Namespace="http://schemas.datacontract.org/2004/07/Database.Model")]
    [System.SerializableAttribute()]
    public partial class Friend : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CastleLegacy.ServerServices.AccountFriends[] AccountFriendsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FriendStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_FriendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CastleLegacy.ServerServices.AccountFriends[] AccountFriends {
            get {
                return this.AccountFriendsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountFriendsField, value) != true)) {
                    this.AccountFriendsField = value;
                    this.RaisePropertyChanged("AccountFriends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendStatus {
            get {
                return this.FriendStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendStatusField, value) != true)) {
                    this.FriendStatusField = value;
                    this.RaisePropertyChanged("FriendStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Friend {
            get {
                return this.Id_FriendField;
            }
            set {
                if ((this.Id_FriendField.Equals(value) != true)) {
                    this.Id_FriendField = value;
                    this.RaisePropertyChanged("Id_Friend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountData", Namespace="http://schemas.datacontract.org/2004/07/Services.DTO")]
    [System.SerializableAttribute()]
    public partial class AccountData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountStatus {
            get {
                return this.AccountStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountStatusField, value) != true)) {
                    this.AccountStatusField = value;
                    this.RaisePropertyChanged("AccountStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Account {
            get {
                return this.Id_AccountField;
            }
            set {
                if ((this.Id_AccountField.Equals(value) != true)) {
                    this.Id_AccountField = value;
                    this.RaisePropertyChanged("Id_Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerServices.IAccount")]
    public interface IAccount {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/AddAccount", ReplyAction="http://tempuri.org/IAccount/AddAccountResponse")]
        int AddAccount(CastleLegacy.ServerServices.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/AddAccount", ReplyAction="http://tempuri.org/IAccount/AddAccountResponse")]
        System.Threading.Tasks.Task<int> AddAccountAsync(CastleLegacy.ServerServices.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/GetAccountByUsername", ReplyAction="http://tempuri.org/IAccount/GetAccountByUsernameResponse")]
        CastleLegacy.ServerServices.AccountData GetAccountByUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/GetAccountByUsername", ReplyAction="http://tempuri.org/IAccount/GetAccountByUsernameResponse")]
        System.Threading.Tasks.Task<CastleLegacy.ServerServices.AccountData> GetAccountByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/GetVerificationCode", ReplyAction="http://tempuri.org/IAccount/GetVerificationCodeResponse")]
        int GetVerificationCode(string username, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/GetVerificationCode", ReplyAction="http://tempuri.org/IAccount/GetVerificationCodeResponse")]
        System.Threading.Tasks.Task<int> GetVerificationCodeAsync(string username, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/ChangePassword", ReplyAction="http://tempuri.org/IAccount/ChangePasswordResponse")]
        int ChangePassword(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/ChangePassword", ReplyAction="http://tempuri.org/IAccount/ChangePasswordResponse")]
        System.Threading.Tasks.Task<int> ChangePasswordAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountChannel : CastleLegacy.ServerServices.IAccount, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountClient : System.ServiceModel.ClientBase<CastleLegacy.ServerServices.IAccount>, CastleLegacy.ServerServices.IAccount {
        
        public AccountClient() {
        }
        
        public AccountClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddAccount(CastleLegacy.ServerServices.Account account) {
            return base.Channel.AddAccount(account);
        }
        
        public System.Threading.Tasks.Task<int> AddAccountAsync(CastleLegacy.ServerServices.Account account) {
            return base.Channel.AddAccountAsync(account);
        }
        
        public CastleLegacy.ServerServices.AccountData GetAccountByUsername(string username) {
            return base.Channel.GetAccountByUsername(username);
        }
        
        public System.Threading.Tasks.Task<CastleLegacy.ServerServices.AccountData> GetAccountByUsernameAsync(string username) {
            return base.Channel.GetAccountByUsernameAsync(username);
        }
        
        public int GetVerificationCode(string username, string email) {
            return base.Channel.GetVerificationCode(username, email);
        }
        
        public System.Threading.Tasks.Task<int> GetVerificationCodeAsync(string username, string email) {
            return base.Channel.GetVerificationCodeAsync(username, email);
        }
        
        public int ChangePassword(string username, string password) {
            return base.Channel.ChangePassword(username, password);
        }
        
        public System.Threading.Tasks.Task<int> ChangePasswordAsync(string username, string password) {
            return base.Channel.ChangePasswordAsync(username, password);
        }
    }
}
