//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleLegacy.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CastleLegacy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already have account? Log in.
        /// </summary>
        public static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Castles.
        /// </summary>
        public static string Castles {
            get {
                return ResourceManager.GetString("Castles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catapults.
        /// </summary>
        public static string Catapults {
            get {
                return ResourceManager.GetString("Catapults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please create a new password; it should consist of at least six characters..
        /// </summary>
        public static string ChangePasswordNewPasswordMessage {
            get {
                return ResourceManager.GetString("ChangePasswordNewPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code has been sent to the provided email. Please check your inbox and enter the code to proceed..
        /// </summary>
        public static string ChangePasswordSentVerificationCodeMessage {
            get {
                return ResourceManager.GetString("ChangePasswordSentVerificationCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kindly furnish your username and email address. This will enable us to dispatch a verification code to your email for authentication purposes..
        /// </summary>
        public static string ChangePasswordVerificationCodeMessage {
            get {
                return ResourceManager.GetString("ChangePasswordVerificationCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change username.
        /// </summary>
        public static string ChangeUsername {
            get {
                return ResourceManager.GetString("ChangeUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm your password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image profile.
        /// </summary>
        public static string ImageProfile {
            get {
                return ResourceManager.GetString("ImageProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username or password is incorrect.
        /// </summary>
        public static string IncorrectAccount {
            get {
                return ResourceManager.GetString("IncorrectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not register yet? Sign Up.
        /// </summary>
        public static string NotRegisterYet {
            get {
                return ResourceManager.GetString("NotRegisterYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password changed.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your password has been successfully changed. Please press &quot;Confirm&quot; to return to the login page..
        /// </summary>
        public static string PasswordChangedMessage {
            get {
                return ResourceManager.GetString("PasswordChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, couldn&apos;t connect to the server. 
        ///Check your internet connection or try again later.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
    }
}
